<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MonitoringDataController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\ProfileController;

// Redirect root route to homepage or login
Route::get('/', function () {
    return Auth::check() ? view('homepage') : redirect()->route('login');
})->name('root');

// Authentication-protected routes
Route::middleware('auth')->group(function () {
    // Homepage route for logged-in users
    Route::get('/homepage', function () {
        return view('homepage');
    })->name('homepage');

    // Profile routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    // Monitoring Data feature
    Route::resource('monitoring-data', MonitoringDataController::class);

    // Manage Patients feature
    Route::resource('patients', PatientController::class);
});

// Auth routes generated by Breeze
require __DIR__.'/auth.php';